version: '3'
services:
    db:
        container_name: db
        image: mysql:8.0.26
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_DATABASE: bddjangoapp
            MYSQL_USER: bddjangoapproot
            MYSQL_PASSWORD: yFrZ9zcfrAx6fVE
            MYSQL_ROOT_PASSWORD: yFrZ9zcfrAx6fVE
        ports:
            - '3308:3306'

    web: 
        container_name: web
        depends_on:
            - db
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
            - 8000:8000

volumes:
    db_data: {}

