# Generated by Django 3.1.1 on 2021-09-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History_adresseip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('nouveau_nom', models.CharField(default=' ', max_length=20)),
                ('nouveau_adresse', models.CharField(default=' ', max_length=20)),
                ('etat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='History_sousreseau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=20)),
                ('nouveau_nom', models.CharField(default=' ', max_length=20)),
                ('nouveau_adresse', models.CharField(default=' ', max_length=20)),
                ('ancien_nom', models.CharField(default=' ', max_length=20)),
                ('ancien_adresse', models.CharField(default=' ', max_length=20)),
                ('date_scan', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='History_vlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=20)),
                ('ancien_nom', models.CharField(default=' ', max_length=20)),
                ('nouveau_nom', models.CharField(default=' ', max_length=20)),
                ('ancien_idvlan', models.CharField(default=' ', max_length=15)),
                ('nouveau_idvlan', models.CharField(default=' ', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idvlan', models.CharField(max_length=15)),
                ('nom', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sousreseau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=20, unique=True)),
                ('taille', models.IntegerField()),
                ('etat', models.BooleanField(default=False)),
                ('derniere_scan', models.DateTimeField(null=True)),
                ('vlan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IPAM.vlan')),
            ],
        ),
        migrations.CreateModel(
            name='Hote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('etat', models.BooleanField(default=False)),
                ('sousreseau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IPAM.sousreseau')),
            ],
        ),
        migrations.CreateModel(
            name='Adresseip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=20)),
                ('etat', models.BooleanField(default=False)),
                ('utliser', models.BooleanField(default=False)),
                ('disponible', models.BooleanField(default=False)),
                ('sousreseau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IPAM.sousreseau')),
            ],
        ),
    ]
